config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  post 'sessions' => 'sessions#create'
  resources :users, except: [:index, :destroy]
  resources :teams, only: [:show, :index]
  resources :trades, except: [:destroy] do
    resources :offers do
      resources :comments
    end
  end
  post 'trades/:id/cancel' => 'trades#cancel', as: :cancel_trade
  post 'trades/:trade_id/offers/:id/accept' => 'offers#accept', as: :trade_offer_accept
  get 'players/:id' => 'players#show', as: :player
  get 'home' => 'home#index', as: :home
  get 'about' => 'home#about'
  get 'signup' => 'users#new', as: :signup
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # using bcrypt's has_secure_password
  has_secure_password

  # relationships
  has_many :trades
  # need a better name for this...
  has_many :partnered_trades, foreign_key: :partner_id, class_name: 'Trade'
  has_many :offers
  has_many :comments

  # validations
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :console, numericality: { only_integer: true, greater_than: 0, less_than: 3 }, presence: true
  # can play with this later, but will have this for now
  # allow nil if there are no trades
  validates :reputation, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10, allow_blank: true }
  # I got this from prof h https://github.com/profh/BreadExpress_Phase_5_Starter/blob/master/app/models/customer.rb#L21
  # can update later
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format"
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :team_name, presence: true, uniqueness: { case_sensitive: false, scope: :console }

  # scopes
  scope :alphabetical, -> { order(:username) }
  scope :for_console, ->(csl) { where(console: csl) }
  scope :for_xbox, -> { where(console: 1) }
  scope :for_playstation, -> { where(console: 2) }
  # might be useful when reputation is implemented
  scope :reputation_above, ->(rep) { where("reputation > ?", rep) }

  # methods
  def xbox_user?
    self.console == 1
  end

  def playstation_user?
    self.console == 2
  end

  def console_name
    self.xbox_user? ? "Xbox One" : "Playstation 4"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :check_not_logged_in, only: [:new, :create]
  before_action :check_user_is_authorized, only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @open_trades = @user.trades.open.includes(:offers, :player)
    @all_trades = @user.trades.includes(:offers, :player)
    @open_offers = @user.offers.open.includes(:trade, :players)
    @accepted_offers = @user.offers.accepted.includes(:trade, :players)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Welcome to HUTrader, #{@user.username}!"
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Successfully updated your account."
    else
      render 'edit'
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :team_name, :console, :email)
  end

  # makes sure nobody is logged in before continuing
  def check_not_logged_in
    if logged_in?
      return authorization_failure("You are already logged in, so you cannot create an account.")
    end
  end

  # makes sure the logged in user is the user that is being edited/updated
  def check_user_is_authorized
    if !logged_in? || current_user.id != @user.id
      return authorization_failure
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <div class='input-field'>
    <%= f.input :username %>
  </div>
  <div class='input-field'>
    <%= f.input :password %>
  </div>
  <div class='input-field'>
    <%= f.input :password_confirmation %>
  </div>
  <div class='input-field'>
    <%= f.input :email %>
  </div>
  <div class='input-field'>
    <%= f.input :team_name %>
  </div>
  <div class='input-field'>
    <%= f.input :console, collection: [["Xbox One", 1],["Playstation 4", 2]], prompt: "Console", label: false %>
  </div>
  <div class='input-field'>
    <%= f.submit nil, class: 'btn blue' %>
  </div>
<% end %>

app/views/users/_offer_tabs.html.erb
<h2>Offers</h2>
<ul class="tabs user-tabs">
  <li class="tab col s3"><a class="active blue-text" href="#open-offers">Open Offers</a></li>
  <li class="tab col s3"><a class="blue-text" href="#accepted-offers">Accepted Offers</a></li>
</ul>
<div id="open-offers">
  <%= render partial: 'user_offers', locals: { offers: @open_offers, description: "open offers"} %>
</div>
<div id="accepted-offers">
  <%= render partial: 'user_offers', locals: { offers: @accepted_offers, description: "accepted offers" } %>
</div>

app/views/users/_trade_tabs.html.erb
<h2>Trades</h2>
<ul class="tabs user-tabs">
  <li class="tab col s3"><a class="active blue-text" href="#open-trades">Open Trades</a></li>
  <li class="tab col s3"><a class="blue-text" href="#all-trades">All Trades</a></li>
</ul>
<div id="open-trades" class="col s12 m12 l8">
  <%= render partial: 'user_trades', locals: { trades: @open_trades, description: "open trades" } %>
</div>
<div id="all-trades" class="col s12 m12 l8">
  <%= render partial: 'user_trades', locals: { trades: @all_trades, description: "trades" } %>
</div>

app/views/users/_user_offers.html.erb
<% if offers.empty? %>
  <em>There are no <%= description %> to display</em>
<% else %>
  <table>
    <thead>
      <th>Player</th>
      <th>Coins</th>
      <th>Offer</th>
      <th></th>
    </thead>
    <tbody>
      <% offers.each do |offer| %>
        <tr>
          <td><%= link_to offer.trade.player.proper_name, offer.trade.player %></td>
          <td><%= offer.coins %></td>
          <td><%= offer.players.map(&:proper_name).to_sentence%></td>
          <td><%= link_to "Details", trade_offer_path(offer.trade, offer) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/_user_trades.html.erb
<% if trades.empty? %>
  <div class="under-slider">
    <em>There are no <%= description %> to display</em>
  </div>
<% else %>
<table class="under-slider">
  <thead>
    <th>Player</th>
    <th>Offers</th>
    <th>Status</th>
    <th></th>
  </thead>
  <tbody>
    <% trades.each do |trade| %>
      <tr>
        <td><%= link_to trade.player.proper_name, trade.player %></td>
        <td><%= trade.offers.count %></td>
        <td><%= trade.status %></td>
        <td><%= link_to "Details", trade %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your Information</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Create your Account</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col s12 m12 l12">
    <h1><%= @user.username %></h1>
  </div>
</div>
<div class="row">
  <div class="col s12 m12 l4">
    <h2>Details</h2>
    <p>Username: <%= @user.username %></p>
    <p>Email: <%= @user.email %></p>
    <p>Console: <%= @user.console_name %></p>
    <p>Team Name: <%= @user.team_name %></p>
    <p>Reputation: <%= @user.reputation.blank? ? "No reviews yet" : @user.reputation %></p>

    <% if logged_in? && @user.id == current_user.id %>
      <%= link_to "Edit", edit_user_path(@user), class: 'btn blue' %>
    <% end%>
  </div>
  <div class="col s12 m12 l8">
    <%= render 'trade_tabs' %>
    <div class="row">
      <div class="col s12 m12 l8">
        <%= render 'offer_tabs' %>
      </div>
    </div>
  </div>
</div>