config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  post 'sessions' => 'sessions#create'
  resources :users, except: [:index, :destroy]
  resources :teams, only: [:show, :index]
  resources :trades, except: [:destroy] do
    resources :offers do
      resources :comments
    end
  end
  post 'trades/:id/cancel' => 'trades#cancel', as: :cancel_trade
  post 'trades/:trade_id/offers/:id/accept' => 'offers#accept', as: :trade_offer_accept
  get 'players/:id' => 'players#show', as: :player
  get 'home' => 'home#index', as: :home
  get 'about' => 'home#about'
  get 'signup' => 'users#new', as: :signup
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  root 'home#index'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  # include for validations
  include Referenceable

  # relationships
  belongs_to :trade
  belongs_to :user
  has_many :offer_players
  has_many :players, through: :offer_players
  has_many :comments

  accepts_nested_attributes_for :offer_players,
    reject_if: lambda {|offer_player| offer_player["player_id"].blank? },
    allow_destroy: true

  # validations
  validates_numericality_of :coins, only_integer: true, greater_than_or_equal_to: 0
  validate -> { reference_exists_in_system(Trade) }
  validate -> { reference_exists_in_system(User) }
  validate :trade_is_not_a_repeat
  validate :trade_is_open
  validate :user_on_same_console

  # scopes
  scope :by_coins, -> { order(coins: :desc) }
  scope :open, -> { joins(:trade).where("trades.status LIKE '#{Trade::STATUSES['open']}'") }
  scope :accepted, -> { joins(:trade).where("trades.partner_id = offers.user_id") }

  private
  # makes sure the same user can't make multiple offers to the same trade
  def trade_is_not_a_repeat
    # see if the record has been created, and has an id assigned
    number_that_can_exist = id.nil? ? 0 : 1
    if Offer.where(user_id: user_id, trade_id: trade_id).length > number_that_can_exist
      errors.add(:user_id, "user has already made an offer for this trade")
    end
  end

  # makes sure a trade is open to offers before creating an offer
  def trade_is_open
    unless trade && trade.status == Trade::STATUSES['open']
      errors.add(:trade_id, "Offers cannot be made unless the trade is open.")
    end
  end

  # makes sure only offers for the same console are valid
  def user_on_same_console
    if user.nil? || trade.nil? || user.console != trade.user.console
      errors.add(:trade_id, "Trade must be for the same console")
    end
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_trade
  before_action :set_offer, except: [:new, :create]
  before_action :check_login, except: :show
  before_action :check_not_trade_creator, only: [:new, :create, :edit, :update]
  before_action :check_user_has_not_offered, only: [:create]
  before_action :check_user_on_same_console, only: [:new, :create]
  before_action :set_offer_associations, only: [:new, :edit]
  before_action :check_correct_user, only: [:edit, :update]

  def new
    users_offer = current_users_offers
    if current_users_offers.any?
      redirect_to edit_trade_offer_path(@trade, current_users_offers.first)
    else
      @offer = Offer.new
      @offer.offer_players.build
    end
  end

  def create
    @offer = Offer.new(offer_params.merge({trade_id: @trade.id, user_id: current_user.id}))
    if @offer.save
      redirect_to trade_offer_path(@trade, @offer), notice: "Your offer has been posted."
    else
      set_offer_associations
      render 'new'
    end
  end

  def show
    @players = @offer.players
    @comments = @offer.comments.includes(:user)
  end

  def edit
  end

  def update
    if @offer.update(offer_params.merge({trade_id: @trade.id, user_id: current_user.id}))
      redirect_to trade_offer_path(@trade, @offer), notice: "Your offer has been updated."
    else
      set_offer_associations
      render 'edit'
    end
  end

  def accept
    if !current_user_posted_trade
      return authorization_failure
    else
      @trade.partner_id = @offer.user_id
      @trade.status = Trade::STATUSES['partnered']
      @trade.save
      redirect_to @trade, notice: "You have accepted this offer."
    end
  end

  private
  def set_offer
    @offer = Offer.find(params[:id])
    if Offer.where(id: @offer.id, trade_id: @trade.id).empty?
      raise ActiveRecord::RecordNotFound.new("The requested offer does not exist.")
    end
  end

  def set_trade
    @trade = Trade.find(params[:trade_id])
  end

  def set_offer_associations
    @user = @trade.user
    @player = @trade.player
    @teams = Team.alphabetical.includes(:players)
  end

  def check_user_has_not_offered
    if current_users_offers.any?
      return authorization_failure("You have already placed a trade offer.")
    end
  end

  def current_users_offers
    Offer.where(user_id: current_user.id, trade_id: @trade.id)
  end

  def check_correct_user
    if current_user.id != @offer.user_id
      return authorization_failure
    end
  end

  def check_not_trade_creator
    if current_user_posted_trade
      return authorization_failure("You can't make an offer to your own trade.")
    end
  end

  def check_user_on_same_console
    user = @trade.user
    if current_user.console != user.console
      return authorization_failure("This trade is for #{user.console_name}")
    end
  end

  def offer_params
    params.require(:offer).permit(:coins, offer_players_attributes: [:id, :player_id, :_destroy])
  end
end

app/helpers/offers_helper.rb
module OffersHelper
  def user_can_post_comment?
    (logged_in?) && (current_user.id == @trade.user_id || current_user.id == @offer.user_id)
  end

  def user_posted_comment?(comment)
    (logged_in?) && (current_user.id == comment.user_id)
  end
end

app/views/offers/_comment_area.html.erb
<h3>Comments</h3>
<% if @comments.empty? %>
  <p>
    This offer has no comments.
  </p>
<% else %>
  <% @comments.each do |comment| %>
    <div class="CommentBox">
      <% if user_posted_comment?(comment) %>
      <div class="CommentBox-posterName CommentBox-posterName--userComment">
        <%= link_to comment.user.username, comment.user %>
        <%= link_to "edit", edit_trade_offer_comment_path(@trade, @offer, comment), class: 'btn-small right' %>
      </div>
      <% else %>
      <div class="CommentBox-posterName">
        <%= link_to comment.user.username, comment.user %>
      </div>
      <% end %>
      <div class="CommentBox-commentBody">
        <%= comment.body %>
      </div>
    </div>
  <% end %>
<% end %>
<% if user_can_post_comment? %>
  <%= link_to "New Comment", new_trade_offer_comment_path(@trade, @offer), class: 'btn green' %>
<% end %>

app/views/offers/_form.html.erb
<%= simple_nested_form_for [@trade, @offer] do |offer_form| %>
  <%= offer_form.input :coins, input_html: { step: 50 } %>
  <div id="offer-players">
    <%= offer_form.simple_fields_for :offer_players do |offer_player_form| %>
      <%= offer_player_form.link_to_remove("x") %>
      <%= offer_player_form.input :player_id, as: :grouped_select, collection: @teams, group_method: :players %>
    <% end %>
  </div>
  <p>
    <%= offer_form.link_to_add("Add Player", :offer_players, data: { target: "#offer-players" }) %>
  </p>
  <%= offer_form.submit nil, class: 'btn blue' %>
<% end %>

app/views/offers/_players_for_offer.html.erb
<% if @players.empty? %>
  There are no players associated with this trade
<% else %>
  <h2>Players</h2>
  <table>
    <thead>
      <th>Player</th>
      <th>Overall</th>
      <th></th>
    </thead>
    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td><%= link_to player.proper_name, player %></td>
          <td><%= player.overall %></td>
          <td><%= link_to "Details", player %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/offers/edit.html.erb
<h1>Edit Your Offer</h1>
<%= render partial: 'form', locals: { action: "create" }%>

app/views/offers/new.html.erb
<h1>New offer for <%= @user.username %>'s <%= @player.proper_name %></h1>

<%= render 'form' %>

app/views/offers/show.html.erb
<h1><%= @offer.user.username %>'s Offer</h1>
<em>Coins: <%= @offer.coins %></em>
<div class="row">
  <div class="col s12 m12 l4">
    <%= render 'players_for_offer' %>
  </div>
  <div class="col s12 m12 l8">
    <%= render 'comment_area' %>
  </div>
</div>
<%= link_to "Trade Details", @trade %>
<% if logged_in? && current_user.id == @offer.user_id %>
  <%= link_to "Edit Offer", edit_trade_offer_path(@trade, @offer) %>
<% end %>

<% if logged_in? && current_user_posted_trade%>
  <%= link_to "Accept Offer", trade_offer_accept_path(@trade, @offer), method: :post %>
<% end %>