config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  post 'sessions' => 'sessions#create'
  resources :users, except: [:index, :destroy]
  resources :teams, only: [:show, :index]
  resources :trades, except: [:destroy] do
    resources :offers do
      resources :comments
    end
  end
  post 'trades/:id/cancel' => 'trades#cancel', as: :cancel_trade
  post 'trades/:trade_id/offers/:id/accept' => 'offers#accept', as: :trade_offer_accept
  get 'players/:id' => 'players#show', as: :player
  get 'home' => 'home#index', as: :home
  get 'about' => 'home#about'
  get 'signup' => 'users#new', as: :signup
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  root 'home#index'

end

app/models/trade.rb
class Trade < ActiveRecord::Base
  include Referenceable
  # relationships
  belongs_to :user
  belongs_to :partner, class_name: "User"
  belongs_to :player
  has_many :offers

  # validations
  validates_numericality_of :user_rating, only_integer: true, allow_nil: true
  validates_numericality_of :partner_rating, only_integer: true, allow_nil: true
  validate -> { reference_exists_in_system(User) }
  validate -> { reference_exists_in_system(Player) }
  validate :partner_and_offer_are_valid?, if: :partner_id_changed?

  # we could get pretty detailed with different statuses, but I figured we need
  # a way to determine trades without a confirmed partner, completed trades to
  # use to see ratings, and closed (canceled). The other two aren't as important
  # for people looking for trades, but are intended for people involved with the trade
  STATUSES = YAML.load_file("#{Rails.root}/config/trade_statuses.yml")
  validates_inclusion_of :status, in: STATUSES.values

  # scopes
  scope :open, -> { where(status: STATUSES["open"]) }
  scope :complete, -> { where(status: STATUSES["complete"]) }
  scope :chronological, -> { order(created_at: :desc) }

  # gets the offer that has been accepted by using the partner_id and the trade's id
  def offer
    Offer.where(user_id: partner_id, trade_id: id).first
  end

  private
  def partner_and_offer_are_valid?
    if User.find_by_id(partner_id).nil? || offer.nil?
      errors.add(:base, "there is no valid trade offer and partner for this trade")
    end
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :cancel]
  before_action :check_login, only: [:new, :create]
  def index
    @open_trades = Trade.open.chronological.includes(:player, :user)
    @xbox_trades = @open_trades.select { |t| t.user.xbox_user? }
    @playstation_trades = @open_trades.select { |t| t.user.playstation_user? }
  end

  def show
    @user = @trade.user
    @partner = @trade.partner
    @player = @trade.player
    @offers = @trade.offers.includes(:players, :user)
  end

  def cancel
    if !logged_in? || !current_user_posted_trade || @trade.status != Trade::STATUSES['open']
      return authorization_failure
    else
      @trade.status = Trade::STATUSES['closed']
      @trade.save
      redirect_to @trade, notice: "Trade has been closed."
    end
  end

  def edit
  end

  def new
    @trade = Trade.new
    @teams = Team.alphabetical.includes(:players)
  end

  def create
    @trade = Trade.new(trade_params)
    if @trade.save
      redirect_to @trade, notice: "Trade for #{@trade.player.proper_name} has been posted."
    else
      render :new
    end
  end

  def update
  end

  private
  def set_trade
    @trade = Trade.find(params[:id])
  end

  def trade_params
    params.require(:trade).permit(:player_id).merge({user_id: current_user.id})
  end
end

app/helpers/trades_helper.rb
module TradesHelper
  def user_can_offer_trade?
    logged_in? && !current_user_posted_trade && @trade.status == Trade::STATUSES['open'] && current_user.console == @user.console
  end
end

app/views/trades/_form.html.erb
<%= simple_form_for @trade do |f| %>
  <%= f.error_notification %>
  <div class='input-field'>
    <%= f.association :player, as: :grouped_select, collection: @teams, group_method: :players, prompt: "Player", label: false %>
  </div>
  <div class='input-field'>
    <%= f.submit nil, class: 'btn blue' %>
  </div>
<% end %>

app/views/trades/_offer_table.html.erb
<table>
  <thead>
    <th>User</th>
    <th>Player(s)</th>
    <th>Coins</th>
    <th></th>
    <% if logged_in? && current_user_posted_trade %>
      <th></th>
    <% end %>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.user.username %></td>
        <td><%= offer.players.map(&:proper_name).to_sentence %></td>
        <td><%= offer.coins %></td>
        <td><%= link_to "View Offer", trade_offer_path(@trade, offer)%></td>
        <% if logged_in? && current_user_posted_trade  && @trade.partner_id.nil? %>
          <th><%= link_to "Accept Offer", trade_offer_accept_path(@trade, offer), method: :post %></th>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trades/_trade_table.html.erb
<h2><%= trade_header %></h2>
<table>
  <thead>
    <th>Player</th>
    <th>User</th>
    <th>Team Name</th>
    <th>Console</th>
  </thead>
  <tbody>
    <% trades.each do |trade| %>
      <tr>
        <td><%= link_to trade.player.proper_name, trade %></td>
        <td><%= link_to trade.user.username, trade.user %></td>
        <td><%= link_to trade.user.team_name, trade.user %></td>
        <td><span class="<%= trade.user.xbox_user? ? 'green' : 'blue'%> white-text console-tag"><%= trade.user.console_name %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trades/edit.html.erb
<h1>Edit Trade</h1>
<p>Still determining the best way to update trade status.</p>

app/views/trades/index.html.erb
<h1>Open Trades</h1>
<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <% if !logged_in? %>
        <li class="tab col s3"><a class="active red-text" href="#all-trades">All</a></li>
        <li class="tab col s3"><a class="blue-text" href="#playstation-trades">Playstation</a></li>
        <li class="tab col s3"><a class="green-text" href="#xbox-trades">Xbox</a></li>
      <% elsif current_user.xbox_user? %>
        <li class="tab col s3"><a class="red-text" href="#all-trades">All</a></li>
        <li class="tab col s3"><a class="blue-text" href="#playstation-trades">Playstation</a></li>
        <li class="tab col s3"><a class="active green-text" href="#xbox-trades">Xbox</a></li>
      <% else %>
        <li class="tab col s3"><a class="red-text" href="#all-trades">All</a></li>
        <li class="tab col s3"><a class="active blue-text" href="#playstation-trades">Playstation</a></li>
        <li class="tab col s3"><a class="green-text" href="#xbox-trades">Xbox</a></li>
      <% end %>

    </ul>
  </div>
  <% if logged_in? %>
    <%= link_to "Add new Trade", :new_trade, class: 'btn green under-slider' %>
  <% end %>
  <div id="all-trades" class="col s12">
    <%= render partial: 'trade_table', locals: { trades: @open_trades, trade_header: 'All Trades' } %>
  </div>
  <div id="playstation-trades" class="col s12">
    <%= render partial: 'trade_table', locals: { trades: @playstation_trades, trade_header: 'Playstation 4 Trades' } %>
  </div>
  <div id="xbox-trades" class="col s12">
    <%= render partial: 'trade_table', locals: { trades: @xbox_trades, trade_header: 'Xbox One Trades' } %>
  </div>
</div>

app/views/trades/new.html.erb
<h1>Create a new trade</h1>
<p>
  Create a trade for <%= current_user.console_name %>
</p>
<%= render 'form' %>

app/views/trades/show.html.erb
<h1>Trade Details</h1>
<p>
  This trade is for <span class="<%= @trade.user.xbox_user? ? 'green' : 'blue'%> white-text"><%= @user.console_name %></span>
</p>
<p>
  Player: <%= link_to @player.proper_name, @player %>
</p>
<p>
  Team Name: <%= @user.team_name %>
</p>
<p>
  HUTrader username: <%= link_to @user.username, @user %>
</p>
<p>
  <% if @trade.status == "Open" %>
    This trade is open to offers.
  <% elsif @trade.status == "Closed" %>
    This trade has been cancelled by <%= @user.username %>.
  <% elsif @trade.status == "Complete" %>
    <%= @user.username %> and <%= link_to @partner.username, @partner %> have completed the trade.
  <% else %>
    <%= @user.username %> has selected <%= link_to @partner.username, @partner %>'s offer.
  <% end%>
</p>
<% if logged_in? && current_user_posted_trade && @trade.status == Trade::STATUSES['open'] %>
<p>
  <%= link_to "Cancel this trade", cancel_trade_path(@trade), method: :post %>
</p>
<% end %>
<div id="offers-detail-area">
  <h3>Offers</h3>
  <% if @offers.empty? %>
  <p>
    There currently no trade offers.
  </p>
  <% else %>
    <%= render 'offer_table' %>
  <% end%>
  <% if user_can_offer_trade? %>
    <%= link_to "Offer Trade", new_trade_offer_path(@trade) %>
  <% end %>
</div>